#!/bin/bash
# Migration script to help users transition to new requirements structure

echo "=== Email Router Requirements Migration ==="
echo ""
echo "The requirements.txt file has been split into environment-specific files:"
echo "  - backend/requirements/base.txt    → Core dependencies"
echo "  - backend/requirements/dev.txt     → Development dependencies"
echo "  - backend/requirements/test.txt    → Testing dependencies"
echo "  - backend/requirements/prod.txt    → Production dependencies"
echo ""
echo "To install dependencies for your environment:"
echo ""
echo "  Development:"
echo "    pip install -r backend/requirements/dev.txt"
echo ""
echo "  Testing:"
echo "    pip install -r backend/requirements/test.txt"
echo ""
echo "  Production:"
echo "    pip install -r backend/requirements/prod.txt"
echo ""
echo "The root requirements.txt file is deprecated and will be removed."
echo ""
echo "For more information, see backend/requirements/README.md"
